name: Run Unit Tests

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install backend dependencies
        run: |
          cd expenses-be
          npm install

      - name: Run backend unit tests
        run: |
          cd expenses-be
          npm test

      - name: Install frontend dependencies
        run: |
          cd expenses-fe
          npm install

      - name: Run frontend unit tests
        run: |
          cd expenses-fe
          npm test
