name: End-to-end tests
on:
  workflow_run:
    workflows: ["Deploy Frontend App"]  
    types:
      - completed
jobs:
  cypress-run:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if unit tests are successful
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
